import { createTheme } from "@mui/material";

export const lightTheme = createTheme({
  typography: {
    h1: {
      fontFamily: "'HK Grotesk'",
      fontStyle: "normal",
      fontWeight: "300",
      fontSize: "96px",
      lineHeight: "116.7%",
      letterSpacing: "-1.5px",
    },
    h2: {
      fontFamily: "'HK Grotesk'",
      fontStyle: "normal",
      fontWeight: "300",
      fontSize: "60px",
      lineHeight: "120%",
      letterSpacing: "-0.5px",
    },
    h3: {
      fontFamily: "'HK Grotesk'",
      fontStyle: "normal",
      fontWeight: "400",
      fontSize: "48px",
      lineHeight: "116.7%",
    },
    h4: {
      fontFamily: "'HK Grotesk'",
      fontStyle: "normal",
      fontWeight: "400",
      fontSize: "34px",
      lineHeight: "123.5%",
      letterSpacing: "0.25px",
    },
    h5: {
      fontFamily: "'HK Grotesk'",
      fontStyle: "normal",
      fontWeight: "400",
      fontSize: "24px",
      lineHeight: "133.4%",
    },
    h6: {
      fontFamily: "'HK Grotesk'",
      fontStyle: "normal",
      fontWeight: "500",
      fontSize: "20px",
      lineHeight: "160%",
      letterSpacing: "0.15px",
    },
    subtitle1: {
      fontFamily: "'HK Grotesk'",
      fontStyle: "normal",
      fontWeight: "400",
      fontSize: "16px",
      lineHeight: "175%",
      letterSpacing: "0.15px",
    },
    subtitle2: {
      fontFamily: "'HK Grotesk'",
      fontStyle: "normal",
      fontWeight: "500",
      fontSize: "14px",
      lineHeight: "157%",
      letterSpacing: "0.1px",
    },
    body1: {
      fontFamily: "'HK Grotesk'",
      fontStyle: "normal",
      fontWeight: "400",
      fontSize: "16px",
      lineHeight: "150%",
      letterSpacing: "0.15px",
    },
    body2: {
      fontFamily: "'HK Grotesk'",
      fontStyle: "normal",
      fontWeight: "400",
      fontSize: "14px",
      lineHeight: "143%",
      letterSpacing: "0.17px",
    },
    caption: {
      display: "block",
      width: "100%",
      fontFamily: "'HK Grotesk'",
      fontStyle: "normal",
      fontWeight: "400",
      fontSize: "12px",
      lineHeight: "166%",
      letterSpacing: "0.4px",
    },
    overline: {
      display: "block",
      width: "100%",
      fontFamily: "'HK Grotesk'",
      fontStyle: "normal",
      fontWeight: "400",
      fontSize: "12px",
      lineHeight: "266%",
      letterSpacing: "1px",
      textTransform: "uppercase",
    },
  },
});
